server:
  port: 8181
spring:
  datasource:
    password: 890610
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.13.110:3306/spring
  application:
    name: microserver-consumer-movie-ribbon
eureka:
  client:
    service-url:
      defaultZone: http://root:890610@localhost:82/eureka
microserver-producer-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule