server:
  port: 82
eureka:
  client:
    service-url:
      defaultZone: http://root:890610@localhost:82/eureka #认证：1、在host前加上“user:password@”表示登录或调用该服务时需要认证
#这两个是把eureka当做服务  不当做客户端
    register-with-eureka: false
    fetch-registry: false
#认证：2、这里是与前面认证匹配在一起的 3、pom中添加spring-cloud-starter-security
security:
  basic:
    enabled: true
  user:
    name: root
    password: 890610
